services:
  - type: web
    name: battlepie-network
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MC_HOST
        value: Node1.mineorange.fun
      - key: MC_PORT
        value: 25569
      - key: MC_BEDROCK_PORT
        value: 19132
      - key: SERVER_SECRET
        value: battlepie_secret_token_123
      - key: DISCORD_CLIENT_ID
        value: 1555211386198696049
      - key: DISCORD_CLIENT_SECRET
        value: U9oUs61e2dEby7ikapN80tQ0ZT3aabJ1
      - key: DISCORD_INVITE
        value: mineorange
