# Mine Orange In-Game Account Linker Configuration
api-url: "https://mineorange.fun/api/auth/link/ingame"

# Server secret token to authenticate requests from your Minecraft server to the website backend
server-secret: "battlepie_secret_token_123"
