name: MineOrangeLink
version: 1.2.0
main: net.battlepie.link.BattlepieLinkPlugin
api-version: '1.20'
author: Mine Orange Network
description: Discord Account Linking Plugin for Mine Orange Network (Cracked + Premium + Bedrock + SkinsRestorer)
softdepend: [SkinsRestorer, Floodgate]
commands:
  link:
    description: Link your Minecraft account with your Mine Orange Discord
    usage: /link <8-digit code>
    aliases: [mclink, discordlink]
  mineorangelink:
    description: Manage MineOrangeLink plugin
    usage: /mineorangelink reload
    permission: mineorange.admin
    aliases: [battlepielink]
