header-footer:
  enabled: true
  designs:
    default:
      header:
      - ''
      - '<shadow:#1D0E46FF>:mineorange_logo:'
      - '<shadow:#000000FF>&fʟɪꜰᴇꜱᴛᴇᴀʟ'
      - ''
      - '<shadow:#000000FF>&a● &f<head:%player%> %player% &8| &a🌎 &f%ping%ms'
      - ''
      - '<shadow:#000000FF>&fPlaying with #00ACFF%online% &fonline players!'
      - ''
      footer:
      - ''
      - '<shadow:#000000FF>%animation:name%'
      - ''
      - '<shadow:#000000FF>%animation:text%'
      - ''
      - '<shadow:#000000FF>%animation:link%'
      - ''
      - '<shadow:#000000FF>%animation:switcher%'
tablist-name-formatting:
  enabled: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  sorting-types:
  - GROUPS:owner,admin,mod,helper,builder,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
playerlist-objective:
  enabled: false
  value: '%health%'
  fancy-value: '%health% #FF0000❤ '
  title: TAB
  render-type: INTEGER
  disable-condition: '%world%=disabledworld'
belowname-objective:
  enabled: true
  value: '0'
  fancy-value: '<shadow:#000000FF><sprite:"minecraft:items":item/emerald> %vault_eco_balance_formatted% &7| &r%animation:belowname%'
  fancy-value-default: NPC
  title: ''
  disable-condition: '%world%=disabledworld'
  view-distance: 10
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: BLUE
      progress: '100'
      text: '#00CBFF&l🏴 NEWS: #00CBFFRecent Server News'
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  delay-on-join-milliseconds: 0
  scoreboards:
    default:
      title: '<shadow:#1D0E46FF>:mineorange_small:'
      lines:
      - ' <shadow:#000000FF>       &fᴍɪɴᴇᴏʀᴀɴɢᴇ.ꜰᴜɴ'
      - ''
      - '<shadow:#000000FF><head:%player%> #ffae00%player%'
      - '<shadow:#000000FF><sprite:"minecraft:items":item/diamond_sword> &fKills: #FF0000%statistic_player_kills%'
      - '<shadow:#000000FF><sprite:"minecraft:gui":mob_effect/raid_omen> &fDeath: #FF8600%deaths%'
      - '<shadow:#000000FF><sprite:"minecraft:items":item/emerald> &fBalance: #22FF00%vault_eco_balance_formatted%'
      - '<shadow:#000000FF><sprite:"minecraft:items":item/totem_of_undying> &fTeam: #00FFFF%seateams_name%'
      - '<shadow:#000000FF><sprite:"minecraft:items":item/clock_63> &fPlaytime: #DDFF00%statistic_time_played:days%d'
      - '<shadow:#000000FF><sprite:"minecraft:gui":mob_effect/dolphins_grace> &fOnline: #00C1FF%online%'
      - ''
      - '<shadow:#000000FF><sprite:"minecraft:gui":icon/ping_5> Ping: %ping% '
      - '<shadow:#000000FF><sprite:"minecraft:items":item/compass_10> %server_time_dd-MM-yyyy%'
      - '<shadow:#000000FF><sprite:"minecraft:items":item/golden_nautilus_armor> &fꜱᴛᴏʀᴇ.ᴍɪɴᴇᴏʀᴀɴɢᴇ.ꜰᴜɴ'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:37e93c8e12cd426cb28fce31969e0674
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      slot-count: 80
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          display-condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
ping-spoof:
  enabled: false
  value: 0
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  update-latency: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
  locale: en-US
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': ' &7[ᴠᴀɴɪꜱʜᴇᴅ]'
    'no': '&r'
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
placeholder-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
permission-refresh-interval: 1000
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
  useSSL: true
proxy-support:
  enabled: true
  channel-name-suffix: TAB
  type: PLUGIN
  plugin:
    name: RedisBungee
  redis:
    url: redis://:password@localhost:6379/0
  rabbitmq:
    exchange: plugin
    url: amqp://guest:guest@localhost:5672/%2F
components:
  minimessage-support: true
  disable-shadow-for-heads: true
config-version: 7
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
compensate-for-packetevents-bug: false
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true
